#!/bin/bash

# include class header
. obj.h
. system.h

# create class object
obj abc

# use object methods
abc.sayHello

myobject.fileName = "file1"

system.stdout.printString "value is"
system.stdout.printValue myobject.fileName
